pyproject.toml: Replace install_requires
install_requires is used with setuptools, with poetry it needs
to use poetry.dependencies

Fixes
poetry.core.constraints.version.exceptions.ParseConstraintError: Could not parse version constraint: robotframework

Signed-off-by: Khem Raj <raj.khem@gmail.com>